### PR TITLE
feat: docker to kubernetes conversion

### PR DESCRIPTION
**Pull request by tejavegesna**
All Docker Files moved to Docker Folder.
Kubernetes folder added

Each Kube Resources has its own file

Nginx & cdcs containers are added in same Pod as they are sharing the same volume

Image Below of how it works on Local
WIPP-Registry-docker-Page-2 (1)

### CODE REVIEW

**Comment by MyleneSimon** [comment]
Hi @tejavegesna, thanks for the PR and detailed explanation!

We are in the process of releasing a new version of WIPP Registry, as the upstream CDCS project is refactoring the way they handle settings, so that we no longer have to mount the whole settings file.
As part of this new release we are providing a Kubernetes deployment configuration (see https://github.com/MyleneSimon/WIPP-Registry-k8s) and we took a slightly different approach for the Django app:
- as mentioned, we are no longer mounting the settings file, and instead just set the required environment variables from a secret,
- we thought about putting the CDCS and Nginx in the same pod as well, but ultimately decided on ditching the Nginx container to simplify the stack since we added the Nginx Ingress, so the Django app is now served by Gunicorn and Whitenoise,
- we added a Job for the superuser creation.

If you get a chance to checkout https://github.com/MyleneSimon/WIPP-Registry-k8s, feedback is welcome!

cc: @sunnielyu @Guillaume-sousa

**Comment by tejavegesna** [comment]
@MyleneSimon 
- Envvars is much better than setting file for sure
- Yes Adding Ingress Controller would be much better and that would be mostly be replaced with AWS ALB Ingress Controller on CI & Production 

Looked at https://github.com/MyleneSimon/WIPP-Registry-k8s Looks Great
Let me know if you need any help

**Comment by MyleneSimon** [comment]
@tejavegesna As discussed offline with Nick, we will be pushing soon a new version of the registry with more configurable options, but https://github.com/MyleneSimon/WIPP-Registry-k8s should be usable for testing if needed (the images used there are already built and pushed to DockerHub)

**Comment by MyleneSimon** [comment]
@tejavegesna the WIPP-Registry-k8s repo is now up at https://github.com/usnistgov/WIPP-Registry-k8s
Please feel free to open related issues and PRs there! Thanks

**Pull request closed without merging**
